import Meals from "@/components/Meals";
import styles from "./styles.module.css"

export const metadata = {
    title: {
        absolute: "Meals"
    },
    description: "Generated by Next-js Post Page",
  };

const MealsPage = () => {
    
    return (
        <div className="p-12 bg-slate-300">
            <h2 className="text-2xl text-orange-600">Choose Your Meals</h2>
            <p className={styles.font_tomato }>Choose meals of you choice by searching....</p>
            <Meals></Meals>
        </div>
    );
};

export default MealsPage;