import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "@/services/AuthProvider";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight: ['400', '500', '700', '900'], subsets: ["latin"] });

export const metadata = {
  title: {
    default: 'Next Js',
    template: '%s | Next Meal'
  },
  description: "Generated by Next js77",
};
// export const metadata = {
//   title: "Next js77 concept",
//   description: "Generated by Next js77",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <AuthProvider>
      <body className={roboto.className}>
          <div className="max-w-7xl mx-auto">
            <Navbar></Navbar>
            {children}
            <Footer></Footer>
          </div>
      </body>
        </AuthProvider>
    </html>
  );
}
