// import { getPosts } from '@/services/postApi';
import Link from 'next/link';
import React from 'react';


export const metadata = {
    title: "Post",
    description: "Generated by Next-js Post Page",
    keywords: ["post", "post page"]
};

const getPosts = async () => {
        const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/posts`)
        const data = await res.json()
        return data
    }



const PostPage = async () => {
    const postsData = await getPosts()
    // console.log(postsData)


    return (
        <div>
            <div>
                <h2 className="mb-1 text-xl font-semibold">All Posts</h2>
                <div className='grid grid-cols-3 gap-5 '>
                    {
                        postsData?.slice(0, 30)?.map(({ title, body, id }) => (
                            <div key={id} className="p-3 border-2 shadow-2xl">
                                <h2 >{id}</h2>
                                <h2 className=''>{title}</h2>
                                <h2>{body}</h2>
                                <button type="button" className="flex items-center justify-center bg-green-600 p-1 space-x-1.5">
                                    <Link href={`/posts/${id}`}>See more</Link>
                                </button>
                            </div>
                        ))
                    }
                </div>
            </div>
        </div>
    );
};

export default PostPage;